apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
spec:
  project: default
  source:
    path: external-dns
    repoURL: git@github.com:bootstrapper-demo-org/k8s-infra.git
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
